version: '2'

services:
  database:
    extends:
      file: ./node_modules/@ubiquits/core/docker/common-services.yml
      service: database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env